// Read-only checks using the installed React/TypeScript packages; no browser needed.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const ts = require('typescript')
const React = require('react')
const { renderToStaticMarkup } = require('react-dom/server')
require('dotenv').config({ path: path.resolve(__dirname, '../../.env') })
const { Pool } = require('pg')
for (const extension of ['.ts', '.tsx']) {
    require.extensions[extension] = (module, filename) => {
        const source = fs.readFileSync(filename, 'utf8')
        const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true, target: ts.ScriptTarget.ES2022 } })
        module._compile(compiled.outputText, filename)
    }
}
require.extensions['.css'] = () => {}
const { default: CategoryPicker } = require('../src/CategoryPicker.tsx')
const { categoryChildren, categoryLabels, categoryTrail } = require('../src/categories.ts')
const { groupMapSellers, groupSellerLocations } = require('../src/map-sellers.ts')
const { clusterMapProducts, mapStage, inViewport } = require('../src/map-clusters.ts')
const pool = new Pool({ connectionString: process.env.DATABASE_URL })
async function main() {
    try {
        const { rows: categories } = await pool.query('SELECT id, parent_id AS "parentId", code, name, image_index AS "imageIndex", sort_order AS "sortOrder" FROM categories WHERE is_active')
        const roots = categoryChildren(categories, null)
        assert.equal(roots.length, 18)
        let leaf = roots.find((item) => item.code === 'market-children')
        while (categoryChildren(categories, leaf.id).length) leaf = categoryChildren(categories, leaf.id)[0]
        const trail = categoryTrail(categories, leaf.id)
        assert.ok(trail.length >= 3)
        const labels = categoryLabels(categories)
        assert.equal(labels.get(leaf.id), trail.map((item) => item.name).join(' › '))
        const selected = renderToStaticMarkup(React.createElement(CategoryPicker, { categories, value: leaf.id, required: true }))
        assert.ok(selected.includes(`name="categoryId" value="${leaf.id}"`))
        assert.ok(selected.includes('role="combobox"'))
        assert.ok(selected.includes(trail.map((item) => item.name).join(' › ')))
        assert.ok(selected.includes('required=""'))
        const empty = renderToStaticMarkup(React.createElement(CategoryPicker, { categories: [], required: true }))
        assert.ok(empty.includes('role="combobox"'))
        assert.ok(empty.includes('required=""'))
        assert.ok(empty.includes('disabled=""'))
        const filter = renderToStaticMarkup(React.createElement(CategoryPicker, { categories, allowAll: true }))
        assert.ok(filter.includes('category-picker-toggle'))
        assert.ok(!filter.includes('required=""'))
        assert.ok(fs.existsSync(path.resolve(__dirname, '../public/categories/category-atlas.png')))
        const makeMarker = (id, owner, latitude = 50.62) => ({ id, title: id, kind: 'product', owner: { id: owner, username: owner }, latitude, longitude: 26.25, distanceBand: 'до 1 км', geoZone: 'Рівне', category: { id: 'category', name: 'Категорія' } })
        const points = [makeMarker('one', 'seller1'), makeMarker('two', 'seller1'), makeMarker('three', 'seller2'), makeMarker('four', 'seller3', 50.63), { ...makeMarker('request', 'buyer'), kind: 'buyRequest' }]
        const grouped = groupMapSellers(points)
        assert.equal(grouped.length, 3)
        assert.equal(grouped.find((seller) => seller.id === 'seller1').products.length, 2)
        assert.deepEqual(groupSellerLocations(grouped).map((group) => group.length).sort(), [1, 2])
        assert.equal(mapStage(12, 1000, 600), 'count')
        assert.equal(mapStage(14, 1000, 600), 'categories')
        assert.equal(mapStage(17, 1000, 600), 'photos')
        assert.equal(mapStage(17, 350, 600), 'photos')
        const products = points.filter((point) => point.kind === 'product')
        const project = (point) => ({ x: point.latitude * 100000, y: point.longitude * 100000 })
        const countClusters = clusterMapProducts(products, 12, project, 'count')
        assert.equal(countClusters.reduce((sum, group) => sum + group.products.length, 0), 4)
        assert.equal(countClusters.length, 2)
        const clusters = clusterMapProducts(products, 17, project, 'photos')
        assert.equal(clusters.length, 2)
        assert.equal(clusters.reduce((sum, group) => sum + group.products.length, 0), 4)
        assert.equal(new Set(clusters.flatMap((group) => group.products.map((point) => point.id))).size, 4)
        assert.ok(inViewport(products[0], { south: 50.61, north: 50.625, west: 26.2, east: 26.3 }))
        assert.ok(!inViewport(products[3], { south: 50.61, north: 50.625, west: 26.2, east: 26.3 }))
        console.log('Adaptive map checks passed: stages, screen size, viewport and conserved product counts.')
        console.log(`Category UI checks passed: ${categories.length} categories, ${roots.length} roots, ${trail.length} selection levels; form IDs, required selection, filter reset and illustrations verified.`)
    } finally { await pool.end() }
}
main().catch((error) => { console.error(error); process.exitCode = 1 })
