INSERT INTO categories (code, name, path)
VALUES
    -- Рослинництво: зернові, бобові та круп'яні культури
    ('wheat', 'Пшениця', 'agriculture/crops/grains/wheat'),
    ('barley', 'Ячмінь', 'agriculture/crops/grains/barley'),
    ('rye', 'Жито', 'agriculture/crops/grains/rye'),
    ('oats', 'Овес', 'agriculture/crops/grains/oats'),
    ('corn', 'Кукурудза', 'agriculture/crops/grains/corn'),
    ('buckwheat', 'Гречка', 'agriculture/crops/grains/buckwheat'),
    ('millet', 'Просо', 'agriculture/crops/grains/millet'),
    ('sorghum', 'Сорго', 'agriculture/crops/grains/sorghum'),
    ('triticale', 'Тритикале', 'agriculture/crops/grains/triticale'),
    ('rice', 'Рис', 'agriculture/crops/grains/rice'),
    ('peas', 'Горох', 'agriculture/crops/pulses/peas'),
    ('soybean', 'Соя', 'agriculture/crops/pulses/soybean'),
    ('chickpeas', 'Нут', 'agriculture/crops/pulses/chickpeas'),
    ('lentils', 'Сочевиця', 'agriculture/crops/pulses/lentils'),
    ('beans', 'Квасоля', 'agriculture/crops/pulses/beans'),
    ('lupin', 'Люпин', 'agriculture/crops/pulses/lupin'),
    ('sunflower', 'Соняшник', 'agriculture/crops/oilseeds/sunflower'),
    ('rapeseed', 'Ріпак', 'agriculture/crops/oilseeds/rapeseed'),
    ('canola', 'Канола', 'agriculture/crops/oilseeds/canola'),
    ('mustard_seed', 'Гірчиця', 'agriculture/crops/oilseeds/mustard'),
    ('flax_seed', 'Льон олійний', 'agriculture/crops/oilseeds/flax'),
    ('camelina', 'Рижій', 'agriculture/crops/oilseeds/camelina'),

    -- Технічні, овочеві, баштанні культури та зелень
    ('sugar_beet', 'Цукровий буряк', 'agriculture/crops/industrial/sugar-beet'),
    ('fodder_beet', 'Кормовий буряк', 'agriculture/crops/industrial/fodder-beet'),
    ('industrial_hemp', 'Промислові коноплі', 'agriculture/crops/industrial/hemp'),
    ('tobacco', 'Тютюн', 'agriculture/crops/industrial/tobacco'),
    ('cotton', 'Бавовник', 'agriculture/crops/industrial/cotton'),
    ('potatoes', 'Картопля', 'agriculture/crops/vegetables/potatoes'),
    ('carrots', 'Морква', 'agriculture/crops/vegetables/carrots'),
    ('beetroot', 'Столовий буряк', 'agriculture/crops/vegetables/beetroot'),
    ('cabbage', 'Капуста', 'agriculture/crops/vegetables/cabbage'),
    ('cauliflower', 'Цвітна капуста', 'agriculture/crops/vegetables/cauliflower'),
    ('broccoli', 'Броколі', 'agriculture/crops/vegetables/broccoli'),
    ('cucumber', 'Огірки', 'agriculture/crops/vegetables/cucumber'),
    ('tomato', 'Помідори', 'agriculture/crops/vegetables/tomato'),
    ('pepper', 'Перець', 'agriculture/crops/vegetables/pepper'),
    ('eggplant', 'Баклажани', 'agriculture/crops/vegetables/eggplant'),
    ('onion', 'Цибуля', 'agriculture/crops/vegetables/onion'),
    ('garlic', 'Часник', 'agriculture/crops/vegetables/garlic'),
    ('squash', 'Кабачки', 'agriculture/crops/vegetables/squash'),
    ('pumpkin', 'Гарбузи', 'agriculture/crops/vegetables/pumpkin'),
    ('radish', 'Редис', 'agriculture/crops/vegetables/radish'),
    ('lettuce', 'Салат', 'agriculture/crops/greens/lettuce'),
    ('spinach', 'Шпинат', 'agriculture/crops/greens/spinach'),
    ('dill', 'Кріп', 'agriculture/crops/greens/dill'),
    ('parsley', 'Петрушка', 'agriculture/crops/greens/parsley'),
    ('basil', 'Базилік', 'agriculture/crops/greens/basil'),
    ('watermelon', 'Кавуни', 'agriculture/crops/melons/watermelon'),
    ('melon', 'Дині', 'agriculture/crops/melons/melon'),

    -- Сади, ягідники, горіхи, гриби та розсадний матеріал
    ('apples', 'Яблука', 'agriculture/horticulture/fruits/apples'),
    ('pears', 'Груші', 'agriculture/horticulture/fruits/pears'),
    ('plums', 'Сливи', 'agriculture/horticulture/fruits/plums'),
    ('cherries', 'Вишні', 'agriculture/horticulture/fruits/cherries'),
    ('sweet_cherries', 'Черешні', 'agriculture/horticulture/fruits/sweet-cherries'),
    ('apricots', 'Абрикоси', 'agriculture/horticulture/fruits/apricots'),
    ('peaches', 'Персики', 'agriculture/horticulture/fruits/peaches'),
    ('grapes', 'Виноград', 'agriculture/horticulture/fruits/grapes'),
    ('quince', 'Айва', 'agriculture/horticulture/fruits/quince'),
    ('currants', 'Смородина', 'agriculture/horticulture/berries/currants'),
    ('gooseberries', 'Аґрус', 'agriculture/horticulture/berries/gooseberries'),
    ('raspberries', 'Малина', 'agriculture/horticulture/berries/raspberries'),
    ('strawberries', 'Полуниця', 'agriculture/horticulture/berries/strawberries'),
    ('blackberries', 'Ожина', 'agriculture/horticulture/berries/blackberries'),
    ('blueberries', 'Лохина', 'agriculture/horticulture/berries/blueberries'),
    ('cranberries', 'Журавлина', 'agriculture/horticulture/berries/cranberries'),
    ('walnuts', 'Волоські горіхи', 'agriculture/horticulture/nuts/walnuts'),
    ('hazelnuts', 'Фундук', 'agriculture/horticulture/nuts/hazelnuts'),
    ('almonds', 'Мигдаль', 'agriculture/horticulture/nuts/almonds'),
    ('mushrooms', 'Їстівні гриби', 'agriculture/horticulture/mushrooms'),
    ('flower_products', 'Квіти та декоративні рослини', 'agriculture/horticulture/flowers'),
    ('seedlings', 'Саджанці та розсада', 'agriculture/planting-material/seedlings'),
    ('seeds', 'Насіння', 'agriculture/planting-material/seeds'),

    -- Кормові культури та живі тварини
    ('hay', 'Сіно', 'agriculture/feed/hay'),
    ('silage', 'Силос', 'agriculture/feed/silage'),
    ('haylage', 'Сінаж', 'agriculture/feed/haylage'),
    ('feed_grain', 'Фуражне зерно', 'agriculture/feed/grain'),
    ('feed_mixes', 'Комбікорм', 'agriculture/feed/mixes'),
    ('cattle', 'Велика рогата худоба', 'agriculture/livestock/cattle'),
    ('dairy_cows', 'Молочні корови', 'agriculture/livestock/cattle/dairy'),
    ('beef_cattle', 'М’ясна худоба', 'agriculture/livestock/cattle/beef'),
    ('calves', 'Телята', 'agriculture/livestock/cattle/calves'),
    ('pigs', 'Свині', 'agriculture/livestock/pigs'),
    ('piglets', 'Поросята', 'agriculture/livestock/pigs/piglets'),
    ('sheep', 'Вівці', 'agriculture/livestock/sheep'),
    ('goats', 'Кози', 'agriculture/livestock/goats'),
    ('horses', 'Коні', 'agriculture/livestock/horses'),
    ('rabbits', 'Кролі', 'agriculture/livestock/rabbits'),
    ('chickens', 'Кури', 'agriculture/poultry/chickens'),
    ('turkeys', 'Індички', 'agriculture/poultry/turkeys'),
    ('ducks', 'Качки', 'agriculture/poultry/ducks'),
    ('geese', 'Гуси', 'agriculture/poultry/geese'),
    ('quails', 'Перепели', 'agriculture/poultry/quails'),
    ('ostriches', 'Страуси', 'agriculture/poultry/ostriches'),
    ('bees', 'Бджолині сім’ї та пакети', 'agriculture/beekeeping/bees'),
    ('queen_bees', 'Бджоломатки', 'agriculture/beekeeping/queen-bees'),
    ('bee_packages', 'Бджолопакети', 'agriculture/beekeeping/packages'),
    ('fish_farming', 'Жива риба та мальок', 'agriculture/aquaculture/live-fish'),
    ('crayfish', 'Раки', 'agriculture/aquaculture/crayfish'),

    -- Продукти тваринництва та бджільництва
    ('beef', 'Яловичина', 'agriculture/animal-products/meat/beef'),
    ('pork', 'Свинина', 'agriculture/animal-products/meat/pork'),
    ('lamb', 'Баранина', 'agriculture/animal-products/meat/lamb'),
    ('goat_meat', 'Козлятина', 'agriculture/animal-products/meat/goat'),
    ('rabbit_meat', 'Кролятина', 'agriculture/animal-products/meat/rabbit'),
    ('poultry_meat', 'М’ясо птиці', 'agriculture/animal-products/meat/poultry'),
    ('milk', 'Молоко', 'agriculture/animal-products/dairy/milk'),
    ('cheese', 'Сири', 'agriculture/animal-products/dairy/cheese'),
    ('cottage_cheese', 'Сир кисломолочний', 'agriculture/animal-products/dairy/cottage-cheese'),
    ('sour_cream', 'Сметана', 'agriculture/animal-products/dairy/sour-cream'),
    ('butter', 'Масло вершкове', 'agriculture/animal-products/dairy/butter'),
    ('yogurt', 'Йогурт та кисломолочні продукти', 'agriculture/animal-products/dairy/yogurt'),
    ('chicken_eggs', 'Курячі яйця', 'agriculture/animal-products/eggs/chicken'),
    ('quail_eggs', 'Перепелині яйця', 'agriculture/animal-products/eggs/quail'),
    ('honey_raw', 'Мед', 'agriculture/animal-products/beekeeping/honey'),
    ('beeswax', 'Бджолиний віск', 'agriculture/animal-products/beekeeping/wax'),
    ('propolis', 'Прополіс', 'agriculture/animal-products/beekeeping/propolis'),
    ('pollen', 'Пилок та перга', 'agriculture/animal-products/beekeeping/pollen'),
    ('royal_jelly', 'Маточне молочко', 'agriculture/animal-products/beekeeping/royal-jelly'),
    ('wool', 'Вовна', 'agriculture/animal-products/raw-materials/wool'),
    ('hides', 'Шкури та хутро', 'agriculture/animal-products/raw-materials/hides'),
    ('manure', 'Гній та органічні добрива', 'agriculture/animal-products/fertilizers/manure'),

    -- Рослинна та фермерська переробка
    ('flour', 'Борошно', 'agriculture/processed/plant/flour'),
    ('groats', 'Крупи', 'agriculture/processed/plant/groats'),
    ('vegetable_oil', 'Рослинні олії', 'agriculture/processed/plant/oils'),
    ('sunflower_meal', 'Шрот і макуха', 'agriculture/processed/feed/meal'),
    ('dried_fruits', 'Сухофрукти', 'agriculture/processed/plant/dried-fruits'),
    ('canned_vegetables', 'Консервовані овочі', 'agriculture/processed/plant/canned-vegetables'),
    ('jams', 'Варення та джеми', 'agriculture/processed/plant/jams'),
    ('pickles', 'Соління та квашені овочі', 'agriculture/processed/plant/pickles'),
    ('wine_materials', 'Виноматеріали та вино', 'agriculture/processed/plant/wine'),
    ('farm_bakery', 'Фермерська випічка', 'agriculture/processed/food/bakery')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    is_active = true,
    updated_at = now();
