import { useState } from 'react'
import PasswordInput from './PasswordInput'
import PhoneInput from './PhoneInput'
import ResendCodeButton from './ResendCodeButton'
import { digitsOf, findCountry, COUNTRIES } from './countries'
const API = import.meta.env.VITE_API_URL ?? ''
async function post(path: string, body: unknown) { const r = await fetch(`${API}${path}`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d?.message ?? 'Не вдалося виконати запит'); return d }
export default function PasswordReset({ onBack }: { onBack: () => void }) {
 const [method,setMethod]=useState<'email'|'phone'>('email'),[countryCode,setCountryCode]=useState('UA'),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[code,setCode]=useState(''),[grant,setGrant]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[sent,setSent]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const contact=method==='email'?email:phone; const c=findCountry(countryCode,COUNTRIES); const validPhone=method==='phone'&&!!c&&digitsOf(phone).length>=c.min&&digitsOf(phone).length<=c.max
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <main className="auth-page password-reset-page"><section className="auth-card"><h2>Відновлення паролю</h2>{!grant&&<><div className="auth-tabs"><button type="button" className={method==='email'?'selected':''} onClick={()=>{setMethod('email');setSent(false)}}>Пошта</button><button type="button" className={method==='phone'?'selected':''} onClick={()=>{setMethod('phone');setSent(false)}}>Телефон</button></div>{method==='email'?<label>Електронна пошта<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>:<PhoneInput countryCode={countryCode} phone={phone} onCountryCode={setCountryCode} onPhone={setPhone}/>} {!sent?<button className="primary-button" disabled={busy||!contact.trim()||(method==='phone'&&!validPhone)} onClick={()=>run(async()=>{await post('/api/auth/password-reset/request',{method,contact,countryCode});setSent(true);setMessage('Якщо контакт підтверджений, код надіслано. Він дійсний 10 хвилин.')})}>Надіслати код</button>:<><label>6-значний код<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code"/></label><button className="primary-button" disabled={busy||code.length!==6} onClick={()=>run(async()=>setGrant((await post('/api/auth/password-reset/verify',{method,contact,code,countryCode})).resetGrant))}>Перевірити код</button><ResendCodeButton onResend={() => run(async () => { await post('/api/auth/password-reset/request', { method, contact, countryCode }); setMessage('Новий код надіслано. Він дійсний 10 хвилин.') })} /></>}</>}{grant&&<><label>Новий пароль<PasswordInput value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Підтвердження пароля<PasswordInput value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="primary-button" onClick={()=>run(async()=>{await post('/api/auth/password-reset/confirm',{resetGrant:grant,password,confirmation});setMessage('Пароль змінено.');setGrant('')})}>Змінити пароль</button></>}{message&&<p className="form-error">{message}</p>}<button type="button" className="text-button" onClick={onBack}>Повернутися до входу</button></section></main>
}


